# Версия docker-compose
version: '3'

volumes:
  pg_data_production:
  # Новый volume — для статических файлов
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: sidside/taski_backend
    env_file: .env
    # Тут подключаем volume к backend
    volumes:
      - static_volume:/backend_static
  frontend:
    image: sidside/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: sidside/taski_gateway
    env_file: .env
    # А тут подключаем volume со статикой к gateway
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80